# Header
menu:
  Home: /
  Archives: /archives
  tags: /tags   
  about: /about
  #commonweal: /404.html
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar right post
sidebar: post
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- weibo

search: 
      path: search.xml
      field: post

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

duoshuo:
   enable: yangyuemeitrue
   short_name: yangyuemei
   
# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: true
  admin_enable: true
  user_id: 6398261151238456000
  admin_nickname: yym
   

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
